# Generated by Django 5.2.12 on 2026-03-27 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaff',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 27, 9, 43, 28, 12143, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
