# Generated by Django 5.2.12 on 2026-03-27 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventstaff_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 11, 3, 58, 573671, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
