# Generated by Django 5.2.12 on 2026-03-26 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_price_tickettype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
